include: package:lint/analysis_options.yaml

analyzer:
  errors:
    must_be_immutable: error
  exclude:
    - lib/generated/**
    - lib/**/*.freezed.dart
    - lib/**/*.g.dart
    
linter:
  rules:
    sort_pub_dependencies: false
    file_names: false