include: package:lint/analysis_options.yaml

analyzer:
  errors:
    must_be_immutable: error
  exclude:
    - lib/generated/**
    
linter:
  rules:
    sort_pub_dependencies: false
    file_names: false